# ft_trans' root service layout composition
name: ft_trans

include:
  - ./services/backend/docker-compose.yml
  - ./services/nginx/docker-compose.yml
  - ./services/website/docker-compose.yml
  # - ./services/vault/docker-compose.yml
