version: "3.9"
name: ft_trans-nginx

networks:
  nginx:

services:
  # Use nginx as our HTTP server and reverse-proxy
  nginx:
    build: .
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      # - "../frontend:/etc/nginx/html"
