name: ft_trans-vault

networks:
  vault:
  nginx:

volumes:
  vault_data:

services:
  # Use HashiCorp's Vault for credentials and secrets management (TLS config, API keys, passwords, etc..).
  vault:
    image: "hashicorp/vault:1.18.1"
    # environment:
      # VAULT_ADDR: http://vault:8200
      # VAULT_DEV_LISTEN_ADDRESS: http://0.0.0.0:8200
      # VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    networks:
      - vault
      - nginx
    volumes:
      - "./config:/vault/config"
      - vault_data:/vault/data:rw
    entrypoint: vault server -config /vault/config/config.hcl
    # ports:
    #   - "8200:8200"
    #   - "8201:8201"
    restart: unless-stopped
