global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  # - job_name: 'node-exporter'
  #     static_configs:
  #       - targets: ['node_exporter:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8098']
