global:
  scrape_interval: 5s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"



scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    basic_auth:
      username: admin
      password: PROM_ADMIN_PASSWD
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'valkey-exporter'
    static_configs:
      - targets: ['valkey-exporter:9121']

  - job_name: 'prometheus-nginx-exporter'
    static_configs:
      - targets: ['prometheus-nginx-exporter:9150']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
