name: ft_trans-backend-website

networks:
  # A network to connect and communicate with rabbitmq
  rabbitmq:
  # The englobing network for nginx-served services
  nginx:

services:
  website-service:
    build:
      context: ..
      dockerfile: website/Dockerfile
    env_file: ../../.env
    networks:
      - rabbitmq
      - nginx
    restart: unless-stopped
    healthcheck:
      test: "wget -qO- http://0.0.0.0:42069/"
      interval: 30s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          ignore:
          - frontend/node_modules
        - action: rebuild
          path: ./service
        - action: rebuild
          path: pyproject.toml
