name: ft_trans-backend-website

networks:
  services:
  nginx:

services:
  website-service:
    build:
      context: ..
      dockerfile: website/Dockerfile
    env_file: ../../.env
    networks:
      - services 
      - nginx
    restart: unless-stopped
    healthcheck:
      test: "wget -qO- http://0.0.0.0:42069/"
      interval: 30s
      timeout: 5s
      retries: 5
