name: ft_trans-nginx

networks:
  nginx:
  nginx_exporter:

services:
  # Use nginx as our HTTP server and reverse-proxy
  nginx:
    build: .
    networks:
      - nginx
      - nginx_exporter
    ports:
      - "8069:80"
      - "8043:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:14321/health || exit 1"]
      timeout: 10s
      retries: 5
      interval: 10s
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - grafana
      - rabbitmq
      - website-service
