name: ft_trans-nginx

networks:
  nginx:
  nginx_internal:
  services:

volumes:
  nginx_logs:
    driver: local

services:
  # Use nginx as our HTTP server and reverse-proxy
  nginx:
    build: .
    networks:
      - nginx
      - nginx_internal
      - services
    ports:
      - "8043:443"      # HTTPS
      - "6943:6943"     # Vault
      # - "14321:14321" # Internal health & metrics
    restart: unless-stopped
    healthcheck:
      test: "wget -qO- http://0.0.0.0:14321/health"
      timeout: 5s
      retries: 3
      interval: 5s
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/servers:/etc/nginx/conf.d"
      - nginx_logs:/nginx-logs
    depends_on:
      - grafana
      - rabbitmq
      - website-service
      - api-service
      - chat-service
