name: ft_trans-nginx

networks:
  nginx:
  nginx_internal:
  services:

volumes:
  nginx_logs:
    driver: local

services:
  # Use nginx as our HTTP server and reverse-proxy
  nginx:
    build: .
    networks:
      - nginx
      - nginx_internal
      - services
    ports:
      - "8043:443"      # HTTPS
      - "6943:6943"     # Vault
      - "14321:14321" # Internal health & metrics
    restart: always
    healthcheck:
      test: "wget -qO- http://0.0.0.0:14321/health"
      timeout: 5s
      retries: 3
      interval: 5s
    volumes:
      - nginx_logs:/nginx-logs
    depends_on:
      - grafana
      - rabbitmq
      # - website-service
      # - api-service
      - chat-service
    develop:
      watch:
        - action: sync+restart
          path: ./config/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: sync+restart
          path: ./config/servers
          target: /etc/nginx/conf.d
