name: ft_trans-nginx

networks:
  nginx:
  nginx_internal:
  services:

volumes:
  nginx_logs:
    driver: local

services:
  # Use nginx as our HTTP server and reverse-proxy
  nginx:
    build: .
    networks:
      - nginx
      - nginx_internal
      - services
    ports:
      - "8069:80"
      - "8043:443"
      - "6943:6943"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:14321/health || exit 1"]
      timeout: 5s
      retries: 5
      interval: 5s
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/servers:/etc/nginx/conf.d"
      - nginx_logs:/nginx-logs
    depends_on:
      #- grafana
      - rabbitmq
      - website-service
      - api-service
