name: ft_trans-services

include:
  # - ./microservices/docker-compose.yml

networks:
  services:
  nginx:
  prometheus:
  valkey:

volumes:
  db:

services:
  # The global database, used for storing users, scores, game data, etc.
  # We're using PostgreSQL as per the subject's requirements
  postgres:
    image: "postgres:17.2-alpine3.21"
    env_file: ../../.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - services 
    ports: #TODO: this is for development only, to remove later
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    build:
      context: containers/valkey
      dockerfile: Dockerfile
    env_file: ../../.env
    networks:
      - valkey
    command:
      - /etc/valkey/valkey-custom.conf
    ports: #TODO: this is for development only, to remove later
      - "6942:6942"
    restart: unless-stopped
    healthcheck:
      test: "valkey-cli -p 6942 ping"
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ is a fast message queue, used for quick inter-process communication
  rabbitmq:
    build:
      context: containers/rabbitmq
      dockerfile: Dockerfile
    env_file: ../../.env
    networks:
      - services
      - nginx
      - prometheus
    ports: #TODO: this is for development only, to remove later
      - "7815:7815"
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10

  # The API service
  api-service:
    build:
      context: .
      dockerfile: service.Dockerfile
      args:
        app_path: api-service
    env_file: ../../.env
    networks:
      - services
    command:
      - "api.wsgi:application"
    expose:
      - "6969"
    restart: unless-stopped
    stop_signal: SIGINT
    healthcheck:
      test: "wget -qO- http://0.0.0.0:6969/health"
      interval: 5s
      timeout: 5s
      retries: 5

  chat-service:
    build:
      context: .
      dockerfile: service.Dockerfile
      args:
        app_path: microservices/chat-service
    env_file: ../../.env
    networks:
      - services
      - valkey
    ports: #TODO: this is for development only, to remove later
      - "18942:18942"
    entrypoint: daphne # Override the entrypoint to use daphne since this is ASGI
    command:
      - "-b"
      - "0.0.0.0"
      - "-p"
      - "18942"
      - "chat_service.asgi:application"
    restart: unless-stopped
    stop_signal: SIGINT
    depends_on:
      valkey:
        condition: service_healthy
