name: ft_trans-backend

include:
  - ./postgres.docker-compose.yml
  - ./services.docker-compose.yml

networks:
  services:
  nginx:
  prometheus:

volumes:
  db:

services:

  # RabbitMQ is a fast message queue, used for quick inter-service communication
  rabbitmq:
    image: "rabbitmq:3.13.4-management"
    env_file: ../../.env
    environment:
      RABBITMQ_ENABLED_PLUGINS_FILE: /rabbitmq_plugins.er
    networks:
      - services
      - nginx
      - prometheus
    volumes:
      - ./rabbitmq/enabled-plugins.er:/rabbitmq_plugins.er
    ports: #TODO: this is for development only, to remove later
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
    restart: unless-stopped
