name: ft_trans-services

include:
  - ./microservices/docker-compose.yml

networks:
  # A network to access postgres databases
  postgres:
  # A network to connect and communicate with rabbitmq
  rabbitmq:
  # The englobing network for nginx-served services
  nginx:
  # A network dedicated to prometheus exporters
  prometheus-exporters:
  # A network for valkey access
  valkey:

volumes:
  db:

services:
  # The global database, used for storing users, scores, game data, etc.
  # We're using PostgreSQL as per the subject's requirements
  postgres:
    image: "postgres:17.2-alpine3.21"
    env_file: ../../.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres
    ports: #TODO: this is for development only, to remove later
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  # A fast key-value store, used for quick storage access
  # Valkey is a fork of Redis, backed by the Linux Foundation, and under an open-source license
  valkey:
    build:
      context: containers/valkey
      dockerfile: Dockerfile
    env_file: ../../.env
    networks:
      - valkey
    command:
      - /etc/valkey/valkey-custom.conf
    ports: #TODO: this is for development only, to remove later
      - "6942:6942"
    restart: unless-stopped
    healthcheck:
      test: "valkey-cli -p 6942 ping"
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ is a fast message queue, used for quick inter-process communication
  rabbitmq:
    build:
      context: containers/rabbitmq
      dockerfile: Dockerfile
    env_file: ../../.env
    networks:
      - rabbitmq
      - nginx
      - prometheus-exporters
    ports: #TODO: this is for development only, to remove later
      - "7815:7815"
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
