name: ft_trans-services

include:
  # - ./microservices/docker-compose.yml

networks:
  services:
  nginx:
  prometheus:
  valkey:

volumes:
  db:

services:
  # The global database, used for storing users, scores, game data, etc.
  # We're using PostgreSQL as per the subject's requirements
  postgres:
    image: "postgres:17.2-alpine3.21"
    env_file: ../../.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - services 
    ports: #TODO: this is for development only, to remove later
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: "valkey/valkey:8.0.2-alpine3.21"
    env_file: ../../.env
    # environment:
    #   - VALKEY_EXTRA_FLAGS=" --port 6942"
    networks:
      - valkey
    ports: #TODO: this is for development only, to remove later
      - "6942:6942"
    restart: unless-stopped
    healthcheck:
      test: "valkey-cli ping"
      interval: 5s
      timeout: 5s
      retries: 5

  # RabbitMQ is a fast message queue, used for quick inter-process communication
  rabbitmq:
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    env_file: ../../.env
    networks:
      - services
      - nginx
      - prometheus
    ports: #TODO: this is for development only, to remove later
      - "7815:7815"
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10

  # The API service
  api-service:
    build:
      context: .
      dockerfile: service.Dockerfile
      args:
        app_name: api-service
    env_file: ../../.env
    command:
      - manage.py
      - runserver
      - "0.0.0.0:6969"
    networks:
      - services
    expose:
      - "6969"
    # ports:
      # - "6969:6969" #TODO: this is for development only, to remove later
    restart: unless-stopped
    stop_signal: SIGINT
    healthcheck:
      test: "wget -qO- http://0.0.0.0:6969/health"
      interval: 5s
      timeout: 5s
      retries: 5
