name: ft_trans-backend

include:
  - ./postgres.docker-compose.yml
  - ./services.docker-compose.yml

networks:
  services:
  nginx:
  prometheus:

volumes:
  db:

services:

  # RabbitMQ is a fast message queue, used for quick inter-service communication
  rabbitmq:
    env_file: ../../.env
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    networks:
      - services
      - nginx
      - prometheus
    # volumes:
    #   - ./rabbitmq/enabled-plugins.er:/etc/rabbitmq/enabled_plugins:ro
    ports: #TODO: this is for development only, to remove later
      - "7815:7815"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
    restart: unless-stopped
