name: ft_trans-backend-services

networks:
  services:

services:
  api-service:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    env_file: ../../.env
    networks:
      - services
    restart: unless-stopped
    stop_signal: SIGINT

  # Authentication service
  # auth-service:
  #   build:
  #     context: ./
  #     dockerfile: ./auth-service/Dockerfile
  #   env_file: ../../.env
  #   networks:
  #     - services
  #   restart: unless-stopped
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   stop_signal: SIGINT

  # Chat service
  chat-service:
    build:
      context: ./
      dockerfile: ./chat-service/Dockerfile
    env_file: ../../.env
    networks:
      - services
    restart: unless-stopped
    # depends_on:
      # user-service:
      #   condition: service_healthy
      # auth-service:
      #   condition: service_healthy
    stop_signal: SIGINT

