name: ft_trans-monitoring

networks:
  prometheus:
  nginx:

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.3.0-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/config.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    networks:
      - prometheus
      - nginx
    restart: unless-stopped
