name: ft_trans-monitoring

include:
  - exporters.docker-compose.yml

networks:
  prometheus:
  nginx:
  nginx_exporter:

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

services:
  # Prometheus is a monitoring system that scrapes data from
  # other services and stores it in a time series database, to be
  # accessed and used by Grafana.
  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=/prometheus/'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - prometheus
      - nginx
    restart: unless-stopped
    healthcheck:
      test: "wget -O /dev/null http://localhost:9090 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3

  # Grafana is a dashboarding and data visualization tool.
  grafana:
    image: grafana/grafana:11.3.0-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/sources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard-providers:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/dashboards
    env_file: ../../.env
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - prometheus
      - nginx
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy
