apiVersion: 1
contactPoints:
    - orgId: 1
      name: Discord Webhook
      receivers:
        - uid: debwr1ni5tou8c
          type: discord
          settings:
            title: "{{- if eq .Status \"firing\" -}}\n  \U0001F525 {{ len .Alerts.Firing }} Firing\n{{- else -}}\n  ✅ {{ len .Alerts.Resolved }} Resolved\n{{- end -}}"
            url: DISCORD_WEBHOOK
            use_discord_username: false
          disableResolveMessage: false

